FROM node:18-buster

RUN apt-get update && \
    apt-get install -y python3 python3-pip

WORKDIR /workspace

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install

COPY . .

RUN pip3 install -r api/requirements.txt

ENV FLASK_APP=api/run.py
ENV FLASK_ENV=development

EXPOSE 3000
EXPOSE 5000

CMD ["pnpm", "run", "dev"]
